name: Build (Linux)

on: [push, workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Setup Ninja
      run: pip3 install ninja

    - name: Setup CUDA
      run: |
        wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.0-1_all.deb
        sudo dpkg -i cuda-keyring_1.0-1_all.deb
        sudo apt-get update
        sudo apt-get install -y cuda-nvcc-12-0 cuda-cudart-dev-12-0 cuda-nvrtc-dev-12-0
        echo "PATH=/usr/local/cuda/bin${PATH:+:${PATH}}" >> $GITHUB_ENV
        echo "CUDA_PATH=/usr/local/cuda" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=/usr/local/cuda/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> $GITHUB_ENV

    - name: Download AviSynth+ headers
      run: |
        wget -q -O avs+.zip https://github.com/AviSynth/AviSynthPlus/archive/refs/tags/v3.7.1a.zip
        unzip -q avs+.zip
        mv AviSynthPlus*/ avisynth+

    - name: Download VapourSynth headers
      run: |
        wget -q -O vs.zip https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth*/ vapoursynth

    - name: Configure
      run: cmake -S . -B build -G Ninja
        -D USE_NVRTC_STATIC=ON
        -D ENABLE_AVISYNTHPLUS=ON
        -D AVISYNTHPLUS_INCLUDE_DIRECTORY="`pwd`/avisynth+/avs_core/include"
        -D ENABLE_VAPOURSYNTH=ON
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="`pwd`/vapoursynth/include"
        -D CMAKE_BUILD_TYPE=Release
        -D CMAKE_CXX_FLAGS_RELEASE="-ffast-math"
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math --resource-usage -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="50;61-real;75-real;86-real;89-real"

    - name: Build
      run: cmake --build build --verbose

    - name: Install
      run: cmake --install build --prefix artifact

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: BM3DCUDA-Linux
        path: artifact
