name: Build (Windows)

on: [push, workflow_dispatch]

jobs:
  build-windows:
    runs-on: windows-2022

    defaults:
      run:
        shell: cmd

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup CUDA
      run: |
        curl -s -o cuda_installer.exe -L https://developer.download.nvidia.com/compute/cuda/11.6.0/network_installers/cuda_11.6.0_windows_network.exe
        cuda_installer.exe -s nvcc_11.6 cudart_11.6 nvrtc_dev_11.6 visual_studio_integration_11.6

    - name: Download AviSynth+ headers
      run: |
        curl -s -o avs+.zip -L https://github.com/AviSynth/AviSynthPlus/archive/refs/tags/v3.7.1a.zip
        unzip -q avs+.zip
        mv AviSynthPlus*/ avisynth+

    - name: Download VapourSynth headers
      run: |
        curl -s -o vs.zip -L https://github.com/vapoursynth/vapoursynth/archive/refs/tags/R57.zip
        unzip -q vs.zip
        mv vapoursynth-*/ vapoursynth/

    - name: Configure
      run: cmake -S . -B build -A x64
        -D USE_NVRTC_STATIC=ON
        -D ENABLE_AVISYNTHPLUS=ON
        -D AVISYNTHPLUS_INCLUDE_DIRECTORY="%cd%\avisynth+\avs_core\include"
        -D ENABLE_VAPOURSYNTH=ON
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="%cd%\vapoursynth\include"
        -D CMAKE_CXX_FLAGS_RELEASE="/fp:fast"
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math --resource-usage -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="35-real;50;61-real;75-real;86"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
        CUDA_PATH_V11_6: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

    - name: Build
      run: cmake --build build --config Release --parallel %NUMBER_OF_PROCESSORS% --verbose
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
        CUDA_PATH_V11_6: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

    - name: Install
      run: cmake --install build --prefix artifact

    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BM3DCUDA-Windows-x64
        path: artifact

    - name: Configure (x86)
      run: cmake -S . -B build_x86 -A Win32 
        -D USE_NVRTC_STATIC=ON
        -D ENABLE_AVISYNTHPLUS=ON
        -D AVISYNTHPLUS_INCLUDE_DIRECTORY="%cd%\avisynth+\avs_core\include"
        -D ENABLE_VAPOURSYNTH=ON
        -D VAPOURSYNTH_INCLUDE_DIRECTORY="%cd%\vapoursynth\include"
        -D CMAKE_CXX_FLAGS_RELEASE="/fp:fast"
        -D CMAKE_CUDA_FLAGS="--threads 0 --use_fast_math --resource-usage -Wno-deprecated-gpu-targets"
        -D CMAKE_CUDA_ARCHITECTURES="35-real;50;61-real;75-real;86"
        -D CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
        CUDA_PATH_V11_6: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

    - name: Build (x86)
      run: cmake --build build_x86 --config Release --parallel %NUMBER_OF_PROCESSORS% --verbose
      env:
        CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
        CUDA_PATH_V11_6: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6

    - name: Install (x86)
      run: cmake --install build_x86 --prefix artifact_x86

    - name: Upload (x86)
      uses: actions/upload-artifact@v2
      with:
        name: BM3DCUDA-Windows-x86
        path: artifact_x86
